trigger: none
pr: none

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    ref: refs/tags/release
    name: 1ESPipelineTemplates/1ESPipelineTemplates
  - repository: InternalVersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions

variables:
- template: /eng/pipelines/variables/common.yml@self
- name: manifest
  value: manifest.samples.json
- name: imageInfoVariant
  value: "-samples"

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceRepositoriesToScan:
        include:
        - repository: InternalVersionsRepo
    pool:
      name: NetCore1ESPool-Internal
      image: 1es-windows-2022
      os: windows
    stages:
    - template: /eng/common/templates/stages/dotnet/build-test-publish-repo.yml@self
      parameters:
        internalProjectName: ${{ variables.internalProjectName }}
        publicProjectName: ${{ variables.publicProjectName }}
        ${{ if eq(variables['System.TeamProject'], 'public') }}:
          buildMatrixCustomBuildLegGroupArgs: --custom-build-leg-group pr-build
